packages:
  - ./platform/web/packages/*
  - ./modules/**/web/packages/*

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild

publicHoistPattern:
  - "@types/*"

linkWorkspacePackages: true
autoInstallPeers: true
preferFrozenLockfile: true
recursiveInstall: true
