/**************************************************************************/
/*  external_global.d.ts                                                  */
/**************************************************************************/
/*                         This file is part of:                          */
/*                             GODOT ENGINE                               */
/*                        https://godotengine.org                         */
/**************************************************************************/
/* Copyright (c) 2014-present Godot Engine contributors (see AUTHORS.md). */
/* Copyright (c) 2007-2014 Juan Linietsky, Ariel Manzur.                  */
/*                                                                        */
/* Permission is hereby granted, free of charge, to any person obtaining  */
/* a copy of this software and associated documentation files (the        */
/* "Software"), to deal in the Software without restriction, including    */
/* without limitation the rights to use, copy, modify, merge, publish,    */
/* distribute, sublicense, and/or sell copies of the Software, and to     */
/* permit persons to whom the Software is furnished to do so, subject to  */
/* the following conditions:                                              */
/*                                                                        */
/* The above copyright notice and this permission notice shall be         */
/* included in all copies or substantial portions of the Software.        */
/*                                                                        */
/* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,        */
/* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF     */
/* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. */
/* IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY   */
/* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,   */
/* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE      */
/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                 */
/**************************************************************************/

// DO NOT MODIFY THIS FILE BY HAND - IT IS AUTO GENERATED BY `external-global-d-ts-builder`.

/* eslint-disable @typescript-eslint/naming-convention, @typescript-eslint/no-deprecated, sort-imports -- Auto-generated file. */

import type {
	addToLibrary as __addToLibrary,
	mergeInto as __mergeInto,
	autoAddDeps as __autoAddDeps,
	wasmTable as __wasmTable,
	err as __err,
	out as __out,
	_malloc as ___malloc,
	_free as ___free,
	getValue as __getValue,
	setValue as __setValue,
	UTF8ToString as __UTF8ToString,
	lengthBytesUTF8 as __lengthBytesUTF8,
	stringToUTF8 as __stringToUTF8,
	stringToUTF8Array as __stringToUTF8Array,
	HEAP8 as __HEAP8,
	HEAP16 as __HEAP16,
	HEAP32 as __HEAP32,
	HEAPU8 as __HEAPU8,
	HEAPU16 as __HEAPU16,
	HEAPU32 as __HEAPU32,
	HEAPF32 as __HEAPF32,
	HEAPF64 as __HEAPF64,
	FS as __FSType,
	FS as __FS,
	IDBFS as __IDBFSType,
	IDBFS as __IDBFS,
	MainLoop as __MainLoopType,
	MainLoop as __MainLoop,
	runtimeKeepalivePush as __runtimeKeepalivePush,
	runtimeKeepalivePop as __runtimeKeepalivePop,
	GL as __GLType,
	GL as __GL,
	_emscripten_webgl_get_current_context as ___emscripten_webgl_get_current_context,
	Module as __Module,
	LibraryManager as __LibraryManagerType,
	LibraryManager as __LibraryManager,
} from "#/external/index.ts";

declare global {
	const addToLibrary: typeof __addToLibrary;
	const mergeInto: typeof __mergeInto;
	const autoAddDeps: typeof __autoAddDeps;
	const wasmTable: typeof __wasmTable;
	const err: typeof __err;
	const out: typeof __out;
	const _malloc: typeof ___malloc;
	const _free: typeof ___free;
	const getValue: typeof __getValue;
	const setValue: typeof __setValue;
	const UTF8ToString: typeof __UTF8ToString;
	const lengthBytesUTF8: typeof __lengthBytesUTF8;
	const stringToUTF8: typeof __stringToUTF8;
	const stringToUTF8Array: typeof __stringToUTF8Array;
	const HEAP8: typeof __HEAP8;
	const HEAP16: typeof __HEAP16;
	const HEAP32: typeof __HEAP32;
	const HEAPU8: typeof __HEAPU8;
	const HEAPU16: typeof __HEAPU16;
	const HEAPU32: typeof __HEAPU32;
	const HEAPF32: typeof __HEAPF32;
	const HEAPF64: typeof __HEAPF64;
	interface FS extends __FSType {}

	const FS: typeof __FS;
	interface FS extends __FSType {}

	const FS: typeof __FS;
	interface IDBFS extends __IDBFSType {}

	const IDBFS: typeof __IDBFS;
	interface IDBFS extends __IDBFSType {}

	const IDBFS: typeof __IDBFS;
	interface MainLoop extends __MainLoopType {}

	const MainLoop: typeof __MainLoop;
	interface MainLoop extends __MainLoopType {}

	const MainLoop: typeof __MainLoop;
	const runtimeKeepalivePush: typeof __runtimeKeepalivePush;
	const runtimeKeepalivePop: typeof __runtimeKeepalivePop;
	interface GL extends __GLType {}

	const GL: typeof __GL;
	interface GL extends __GLType {}

	const GL: typeof __GL;
	const _emscripten_webgl_get_current_context: typeof ___emscripten_webgl_get_current_context;
	const Module: typeof __Module;
	interface LibraryManager extends __LibraryManagerType {}

	const LibraryManager: typeof __LibraryManager;
	interface LibraryManager extends __LibraryManagerType {}

	const LibraryManager: typeof __LibraryManager;
}

export {};
