/**************************************************************************/
/*  external-global.d.ts                                                  */
/**************************************************************************/
/*                         This file is part of:                          */
/*                             GODOT ENGINE                               */
/*                        https://godotengine.org                         */
/**************************************************************************/
/* Copyright (c) 2014-present Godot Engine contributors (see AUTHORS.md). */
/* Copyright (c) 2007-2014 Juan Linietsky, Ariel Manzur.                  */
/*                                                                        */
/* Permission is hereby granted, free of charge, to any person obtaining  */
/* a copy of this software and associated documentation files (the        */
/* "Software"), to deal in the Software without restriction, including    */
/* without limitation the rights to use, copy, modify, merge, publish,    */
/* distribute, sublicense, and/or sell copies of the Software, and to     */
/* permit persons to whom the Software is furnished to do so, subject to  */
/* the following conditions:                                              */
/*                                                                        */
/* The above copyright notice and this permission notice shall be         */
/* included in all copies or substantial portions of the Software.        */
/*                                                                        */
/* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,        */
/* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF     */
/* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. */
/* IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY   */
/* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,   */
/* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE      */
/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                 */
/**************************************************************************/

// DO NOT MODIFY THIS FILE BY HAND - IT IS AUTO GENERATED BY `external-global-d-ts-builder`.

/* eslint-disable @typescript-eslint/naming-convention, sort-imports -- Auto-generated file. */

import type {
	GodotWebXR as __GodotWebXR,
	MainLoop as __MainLoop,
	__EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop,
} from "#/external/index.ts";
type __Global_GodotAudioType = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["GodotAudio"];
type __Global_GodotAudioScriptType = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["GodotAudioScript"];
type __Global_GodotAudioWorkletType = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["GodotAudioWorklet"];
type __Global_GodotConfigType = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["GodotConfig"];
type __Global_GodotDisplayType = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["GodotDisplay"];
type __Global_GodotDisplayCursorType = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["GodotDisplayCursor"];
type __Global_GodotDisplayScreenType = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["GodotDisplayScreen"];
type __Global_GodotDisplayVKType = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["GodotDisplayVK"];
type __Global_GodotEvalType = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["GodotEval"];
type __Global_GodotEventListenersType = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["GodotEventListeners"];
type __Global_GodotFSType = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["GodotFS"];
type __Global_GodotFetchType = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["GodotFetch"];
type __Global_GodotIMEType = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["GodotIME"];
type __Global_GodotInputType = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["GodotInput"];
type __Global_GodotInputDragDropType = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["GodotInputDragDrop"];
type __Global_GodotInputGamepadsType = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["GodotInputGamepads"];
type __Global_GodotJSWrapperType = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["GodotJSWrapper"];
type __Global_GodotOSType = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["GodotOS"];
type __Global_GodotPWAType = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["GodotPWA"];
type __Global_GodotRuntimeType = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["GodotRuntime"];
type __Global_GodotWebGL2Type = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["GodotWebGL2"];
type __Global_GodotWebMidiType = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["GodotWebMidi"];
type __Global_IDHandlerType = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["IDHandler"];
type __Global_FSType = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["FS"];
type __Global_GLType = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["GL"];
type __Global_HEAP16Type = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["HEAP16"];
type __Global_HEAP32Type = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["HEAP32"];
type __Global_HEAP8Type = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["HEAP8"];
type __Global_HEAPF32Type = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["HEAPF32"];
type __Global_HEAPF64Type = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["HEAPF64"];
type __Global_HEAPU16Type = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["HEAPU16"];
type __Global_HEAPU32Type = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["HEAPU32"];
type __Global_HEAPU8Type = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["HEAPU8"];
type __Global_IDBFSType = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["IDBFS"];
type __Global_LibraryManagerType = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["LibraryManager"];
type __Global_ModuleType = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["Module"];
type __Global_UTF8ToStringType = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["UTF8ToString"];
type __Global__emscripten_webgl_get_current_contextType =
	__EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["_emscripten_webgl_get_current_context"];
type __Global__freeType = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["_free"];
type __Global__mallocType = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["_malloc"];
type __Global_addToLibraryType = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["addToLibrary"];
type __Global_autoAddDepsType = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["autoAddDeps"];
type __Global_errType = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["err"];
type __Global_getValueType = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["getValue"];
type __Global_lengthBytesUTF8Type = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["lengthBytesUTF8"];
type __Global_mergeIntoType = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["mergeInto"];
type __Global_outType = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["out"];
type __Global_runtimeKeepalivePopType = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["runtimeKeepalivePop"];
type __Global_runtimeKeepalivePushType = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["runtimeKeepalivePush"];
type __Global_setValueType = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["setValue"];
type __Global_stringToUTF8Type = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["stringToUTF8"];
type __Global_stringToUTF8ArrayType = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["stringToUTF8Array"];
type __Global_wasmTableType = __EXTRACT_TO_GLOBAL__ExternalTypesWithoutMainLoop["wasmTable"];

declare global {
	const GodotWebXR: typeof __GodotWebXR;
	const MainLoop: typeof __MainLoop;
	const GodotAudio: __Global_GodotAudioType;
	const GodotAudioScript: __Global_GodotAudioScriptType;
	const GodotAudioWorklet: __Global_GodotAudioWorkletType;
	const GodotConfig: __Global_GodotConfigType;
	const GodotDisplay: __Global_GodotDisplayType;
	const GodotDisplayCursor: __Global_GodotDisplayCursorType;
	const GodotDisplayScreen: __Global_GodotDisplayScreenType;
	const GodotDisplayVK: __Global_GodotDisplayVKType;
	const GodotEval: __Global_GodotEvalType;
	const GodotEventListeners: __Global_GodotEventListenersType;
	const GodotFS: __Global_GodotFSType;
	const GodotFetch: __Global_GodotFetchType;
	const GodotIME: __Global_GodotIMEType;
	const GodotInput: __Global_GodotInputType;
	const GodotInputDragDrop: __Global_GodotInputDragDropType;
	const GodotInputGamepads: __Global_GodotInputGamepadsType;
	const GodotJSWrapper: __Global_GodotJSWrapperType;
	const GodotOS: __Global_GodotOSType;
	const GodotPWA: __Global_GodotPWAType;
	const GodotRuntime: __Global_GodotRuntimeType;
	const GodotWebGL2: __Global_GodotWebGL2Type;
	const GodotWebMidi: __Global_GodotWebMidiType;
	const IDHandler: __Global_IDHandlerType;

	interface FS extends __Global_FSType {}

	const FS: __Global_FSType;

	interface GL extends __Global_GLType {}

	const GL: __Global_GLType;
	const HEAP16: __Global_HEAP16Type;
	const HEAP32: __Global_HEAP32Type;
	const HEAP8: __Global_HEAP8Type;
	const HEAPF32: __Global_HEAPF32Type;
	const HEAPF64: __Global_HEAPF64Type;
	const HEAPU16: __Global_HEAPU16Type;
	const HEAPU32: __Global_HEAPU32Type;
	const HEAPU8: __Global_HEAPU8Type;

	interface IDBFS extends __Global_IDBFSType {}

	const IDBFS: __Global_IDBFSType;

	interface LibraryManager extends __Global_LibraryManagerType {}

	const LibraryManager: __Global_LibraryManagerType;
	const Module: __Global_ModuleType;
	const UTF8ToString: __Global_UTF8ToStringType;
	const _emscripten_webgl_get_current_context: __Global__emscripten_webgl_get_current_contextType;
	const _free: __Global__freeType;
	const _malloc: __Global__mallocType;
	const addToLibrary: __Global_addToLibraryType;
	const autoAddDeps: __Global_autoAddDepsType;
	const err: __Global_errType;
	const getValue: __Global_getValueType;
	const lengthBytesUTF8: __Global_lengthBytesUTF8Type;
	const mergeInto: __Global_mergeIntoType;
	const out: __Global_outType;
	const runtimeKeepalivePop: __Global_runtimeKeepalivePopType;
	const runtimeKeepalivePush: __Global_runtimeKeepalivePushType;
	const setValue: __Global_setValueType;
	const stringToUTF8: __Global_stringToUTF8Type;
	const stringToUTF8Array: __Global_stringToUTF8ArrayType;
	const wasmTable: __Global_wasmTableType;
}

export {};
