/**************************************************************************/
/*  external_global.d.ts                                                  */
/**************************************************************************/
/*                         This file is part of:                          */
/*                             GODOT ENGINE                               */
/*                        https://godotengine.org                         */
/**************************************************************************/
/* Copyright (c) 2014-present Godot Engine contributors (see AUTHORS.md). */
/* Copyright (c) 2007-2014 Juan Linietsky, Ariel Manzur.                  */
/*                                                                        */
/* Permission is hereby granted, free of charge, to any person obtaining  */
/* a copy of this software and associated documentation files (the        */
/* "Software"), to deal in the Software without restriction, including    */
/* without limitation the rights to use, copy, modify, merge, publish,    */
/* distribute, sublicense, and/or sell copies of the Software, and to     */
/* permit persons to whom the Software is furnished to do so, subject to  */
/* the following conditions:                                              */
/*                                                                        */
/* The above copyright notice and this permission notice shall be         */
/* included in all copies or substantial portions of the Software.        */
/*                                                                        */
/* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,        */
/* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF     */
/* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. */
/* IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY   */
/* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,   */
/* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE      */
/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                 */
/**************************************************************************/

// DO NOT MODIFY THIS FILE BY HAND - IT IS AUTO GENERATED BY `external-global-d-ts-builder`.

/* eslint-disable @typescript-eslint/naming-convention, @typescript-eslint/no-deprecated, sort-imports -- Auto-generated file. */

import type {
	FS as __FSType,
	FS as __FS,
	GL as __GLType,
	GL as __GL,
	HEAP16 as __HEAP16,
	HEAP32 as __HEAP32,
	HEAP8 as __HEAP8,
	HEAPF32 as __HEAPF32,
	HEAPF64 as __HEAPF64,
	HEAPU16 as __HEAPU16,
	HEAPU32 as __HEAPU32,
	HEAPU8 as __HEAPU8,
	IDBFS as __IDBFSType,
	IDBFS as __IDBFS,
	LibraryManager as __LibraryManagerType,
	LibraryManager as __LibraryManager,
	MainLoop as __MainLoopType,
	MainLoop as __MainLoop,
	Module as __Module,
	UTF8ToString as __UTF8ToString,
	_emscripten_webgl_get_current_context as ___emscripten_webgl_get_current_context,
	_free as ___free,
	_malloc as ___malloc,
	addToLibrary as __addToLibrary,
	autoAddDeps as __autoAddDeps,
	err as __err,
	getValue as __getValue,
	lengthBytesUTF8 as __lengthBytesUTF8,
	mergeInto as __mergeInto,
	out as __out,
	runtimeKeepalivePop as __runtimeKeepalivePop,
	runtimeKeepalivePush as __runtimeKeepalivePush,
	setValue as __setValue,
	stringToUTF8 as __stringToUTF8,
	stringToUTF8Array as __stringToUTF8Array,
	wasmTable as __wasmTable,
	addToLibrary as __addToLibrary,
	mergeInto as __mergeInto,
	autoAddDeps as __autoAddDeps,
	wasmTable as __wasmTable,
	err as __err,
	out as __out,
	_malloc as ___malloc,
	_free as ___free,
	getValue as __getValue,
	setValue as __setValue,
	UTF8ToString as __UTF8ToString,
	lengthBytesUTF8 as __lengthBytesUTF8,
	stringToUTF8 as __stringToUTF8,
	stringToUTF8Array as __stringToUTF8Array,
	HEAP8 as __HEAP8,
	HEAP16 as __HEAP16,
	HEAP32 as __HEAP32,
	HEAPU8 as __HEAPU8,
	HEAPU16 as __HEAPU16,
	HEAPU32 as __HEAPU32,
	HEAPF32 as __HEAPF32,
	HEAPF64 as __HEAPF64,
	FS as __FSType,
	FS as __FS,
	IDBFS as __IDBFSType,
	IDBFS as __IDBFS,
	MainLoop as __MainLoopType,
	MainLoop as __MainLoop,
	runtimeKeepalivePush as __runtimeKeepalivePush,
	runtimeKeepalivePop as __runtimeKeepalivePop,
	GL as __GLType,
	GL as __GL,
	_emscripten_webgl_get_current_context as ___emscripten_webgl_get_current_context,
	Module as __Module,
	LibraryManager as __LibraryManagerType,
	LibraryManager as __LibraryManager,
	GodotRuntime as __GodotRuntime,
	GodotOS as __GodotOS,
	GodotFS as __GodotFS,
	GodotAudio as __GodotAudio,
	GodotAudioWorklet as __GodotAudioWorklet,
	GodotAudioScript as __GodotAudioScript,
	GodotDisplayVK as __GodotDisplayVK,
	GodotDisplayCursor as __GodotDisplayCursor,
	GodotDisplayScreen as __GodotDisplayScreen,
	GodotDisplay as __GodotDisplay,
	GodotEval as __GodotEval,
	GodotFetch as __GodotFetch,
	GodotJSWrapper as __GodotJSWrapper,
	GodotEventListeners as __GodotEventListeners,
	GodotConfig as __GodotConfig,
	GodotPWA as __GodotPWA,
	IDHandler as __IDHandler,
	GodotIME as __GodotIME,
	GodotInputGamepads as __GodotInputGamepads,
	GodotInputDragDrop as __GodotInputDragDrop,
	GodotInput as __GodotInput,
	GodotWebGL2 as __GodotWebGL2,
	GodotWebMidi as __GodotWebMidi,
} from "#/external/index.ts";

declare global {
	interface FS extends __FSType {}

	const FS: typeof __FS;
	interface FS extends __FSType {}

	const FS: typeof __FS;
	interface GL extends __GLType {}

	const GL: typeof __GL;
	interface GL extends __GLType {}

	const GL: typeof __GL;
	const HEAP16: typeof __HEAP16;
	const HEAP32: typeof __HEAP32;
	const HEAP8: typeof __HEAP8;
	const HEAPF32: typeof __HEAPF32;
	const HEAPF64: typeof __HEAPF64;
	const HEAPU16: typeof __HEAPU16;
	const HEAPU32: typeof __HEAPU32;
	const HEAPU8: typeof __HEAPU8;
	interface IDBFS extends __IDBFSType {}

	const IDBFS: typeof __IDBFS;
	interface IDBFS extends __IDBFSType {}

	const IDBFS: typeof __IDBFS;
	interface LibraryManager extends __LibraryManagerType {}

	const LibraryManager: typeof __LibraryManager;
	interface LibraryManager extends __LibraryManagerType {}

	const LibraryManager: typeof __LibraryManager;
	interface MainLoop extends __MainLoopType {}

	const MainLoop: typeof __MainLoop;
	interface MainLoop extends __MainLoopType {}

	const MainLoop: typeof __MainLoop;
	const Module: typeof __Module;
	const UTF8ToString: typeof __UTF8ToString;
	const _emscripten_webgl_get_current_context: typeof ___emscripten_webgl_get_current_context;
	const _free: typeof ___free;
	const _malloc: typeof ___malloc;
	const addToLibrary: typeof __addToLibrary;
	const autoAddDeps: typeof __autoAddDeps;
	const err: typeof __err;
	const getValue: typeof __getValue;
	const lengthBytesUTF8: typeof __lengthBytesUTF8;
	const mergeInto: typeof __mergeInto;
	const out: typeof __out;
	const runtimeKeepalivePop: typeof __runtimeKeepalivePop;
	const runtimeKeepalivePush: typeof __runtimeKeepalivePush;
	const setValue: typeof __setValue;
	const stringToUTF8: typeof __stringToUTF8;
	const stringToUTF8Array: typeof __stringToUTF8Array;
	const wasmTable: typeof __wasmTable;
	const addToLibrary: typeof __addToLibrary;
	const mergeInto: typeof __mergeInto;
	const autoAddDeps: typeof __autoAddDeps;
	const wasmTable: typeof __wasmTable;
	const err: typeof __err;
	const out: typeof __out;
	const _malloc: typeof ___malloc;
	const _free: typeof ___free;
	const getValue: typeof __getValue;
	const setValue: typeof __setValue;
	const UTF8ToString: typeof __UTF8ToString;
	const lengthBytesUTF8: typeof __lengthBytesUTF8;
	const stringToUTF8: typeof __stringToUTF8;
	const stringToUTF8Array: typeof __stringToUTF8Array;
	const HEAP8: typeof __HEAP8;
	const HEAP16: typeof __HEAP16;
	const HEAP32: typeof __HEAP32;
	const HEAPU8: typeof __HEAPU8;
	const HEAPU16: typeof __HEAPU16;
	const HEAPU32: typeof __HEAPU32;
	const HEAPF32: typeof __HEAPF32;
	const HEAPF64: typeof __HEAPF64;
	interface FS extends __FSType {}

	const FS: typeof __FS;
	interface FS extends __FSType {}

	const FS: typeof __FS;
	interface IDBFS extends __IDBFSType {}

	const IDBFS: typeof __IDBFS;
	interface IDBFS extends __IDBFSType {}

	const IDBFS: typeof __IDBFS;
	interface MainLoop extends __MainLoopType {}

	const MainLoop: typeof __MainLoop;
	interface MainLoop extends __MainLoopType {}

	const MainLoop: typeof __MainLoop;
	const runtimeKeepalivePush: typeof __runtimeKeepalivePush;
	const runtimeKeepalivePop: typeof __runtimeKeepalivePop;
	interface GL extends __GLType {}

	const GL: typeof __GL;
	interface GL extends __GLType {}

	const GL: typeof __GL;
	const _emscripten_webgl_get_current_context: typeof ___emscripten_webgl_get_current_context;
	const Module: typeof __Module;
	interface LibraryManager extends __LibraryManagerType {}

	const LibraryManager: typeof __LibraryManager;
	interface LibraryManager extends __LibraryManagerType {}

	const LibraryManager: typeof __LibraryManager;
	const GodotRuntime: typeof __GodotRuntime;
	const GodotOS: typeof __GodotOS;
	const GodotFS: typeof __GodotFS;
	const GodotAudio: typeof __GodotAudio;
	const GodotAudioWorklet: typeof __GodotAudioWorklet;
	const GodotAudioScript: typeof __GodotAudioScript;
	const GodotDisplayVK: typeof __GodotDisplayVK;
	const GodotDisplayCursor: typeof __GodotDisplayCursor;
	const GodotDisplayScreen: typeof __GodotDisplayScreen;
	const GodotDisplay: typeof __GodotDisplay;
	const GodotEval: typeof __GodotEval;
	const GodotFetch: typeof __GodotFetch;
	const GodotJSWrapper: typeof __GodotJSWrapper;
	const GodotEventListeners: typeof __GodotEventListeners;
	const GodotConfig: typeof __GodotConfig;
	const GodotPWA: typeof __GodotPWA;
	const IDHandler: typeof __IDHandler;
	const GodotIME: typeof __GodotIME;
	const GodotInputGamepads: typeof __GodotInputGamepads;
	const GodotInputDragDrop: typeof __GodotInputDragDrop;
	const GodotInput: typeof __GodotInput;
	const GodotWebGL2: typeof __GodotWebGL2;
	const GodotWebMidi: typeof __GodotWebMidi;
}

export {};
