#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_webrtc = env_modules.Clone()

if env["platform"] == "web":
    from misc.utility.platform.web import add_emscripten_library

    # Our JavaScript/C++ interface.
    add_emscripten_library(env, "webrtc", env.File("emscripten/libwebrtc.ts"))

env_webrtc.add_source_files(env.modules_sources, "*.cpp")
