#!/usr/bin/env python
from misc.utility.scons_hints import *

from methods import add_emscripten_library

Import("env")
Import("env_modules")

env_webrtc = env_modules.Clone()

if env["platform"] == "web":
    # Our JavaScript/C++ interface.
    add_emscripten_library(env, "webrtc", "emscripten/libwebrtc.ts")

env_webrtc.add_source_files(env.modules_sources, "*.cpp")
