#!/usr/bin/env python
from misc.utility.scons_hints import *

from methods import add_emscripten_library

Import("env")
Import("env_modules")

if env["platform"] == "web":
    add_emscripten_library(env, "webxr", "native/libwebxr.ts")

env_webxr = env_modules.Clone()
env_webxr.add_source_files(env.modules_sources, "*.cpp")
