#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

if env["platform"] == "web":
    from misc.utility.platform.web import add_emscripten_library

    add_emscripten_library(env, "webxr", env.File("native/libwebxr.ts"))

env_webxr = env_modules.Clone()
env_webxr.add_source_files(env.modules_sources, "*.cpp")
