#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

if env["platform"] == "web":
    env.AddJSLibraries(["web/packages/emscripten-library-webxr/dist/emscripten-library-webxr.js"])

env_webxr = env_modules.Clone()
env_webxr.add_source_files(env.modules_sources, "*.cpp")
